title: Yang Liu # your name (or website title) here
logo: "/images/YangLiu.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   
  <br>
  in _config.yml 
  <br><br>
  <a href="https://www.linkedin.com/in/yang-liu-715194217/">LinkedIn</a> 
  <br>
  <a href="https://bowen.finance/cv/" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://github.com/yal521">GitHub</a>  
theme: jekyll-theme-minimal
