title: Yang Liu # your name (or website title) here
logo: "/images/YangLiu.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <br><br>
  <a href="https://www.linkedin.com/in/yang-liu-715194217/">LinkedIn</a> 
  <br>
  <a href="https://github.com/yal521/YangLiu/blob/fc7aede14221fb772ccbd4e0563eb1ee9929c082/pdf/Yang%20Liu.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://github.com/yal521">GitHub</a>  
theme: jekyll-theme-minimal
